name: ablog
favicon: null
layout_spectrum: 0.87878
typography_spectrum: 0.81565
title: 'tech luddite & internet buzzkill'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151a16'
    - '#54595d'
    - '#fdfdfe'
    - '#a3a3a5'
    - '#cbd3e0'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
