name: ablog
favicon: null
layout_spectrum: 0.87878
typography_spectrum: 0.81565
title: 'tech luddite & internet buzzkill'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#162930'
    - '#586e6b'
    - '#89978a'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
