name: ablog
favicon: null
layout_spectrum: 0.74694
typography_spectrum: 1
title: 'now in responsive flavors!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151a16'
    - '#54595d'
    - '#fdfdfe'
    - '#a3a3a5'
    - '#cbd3e0'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
