name: ablog
favicon: null
layout_spectrum: 0.74694
typography_spectrum: 1
title: 'now in responsive flavors!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddd4cb'
    - '#aca19b'
    - '#616169'
    - '#3b3e45'
    - '#02091c'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
